import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Footer } from "./components/input/footer/footer";
import NavList from './components/header/navList'; // Import NavList
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: "--font-poppins"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <Footer classname="fixed bottom-0"></Footer>
      </body>
    </html>
  );
}
